name: CI - Symfony

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uuser -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo_mysql, intl, zip

      - name: Install dependencies
        run: composer install --no-scripts --no-interaction

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=mysql://user:password@mysql:3306/symfony" >> $GITHUB_ENV

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        run: ./vendor/bin/phpunit
